angular/universal

modules/universal/server/src/render.ts

Missing dependencies in preboot server eg.:
preboot/src/server/client_code_generator.ts (q, gulp-uglify etc.)
Dependencies are in preboot/node_modules

fix(render): fix wrong import

---

modules/universal/server/src/helper.ts
modules/universal/server/src/platform/node.ts

This fixes a issue with the selector with attrs RegExp and template string (https://github.com/angular/universal/commit/787d98c90dfdb713c1e80a97764c51424ade967b)
Before:
```js
var regExpSelect = "<" + escapeRegExp(selector) + "[^>]*>([sS]*?)</" + escapeRegExp(selector) + ">";
```
After:
```js
var regExpSelect = "<" + escapeRegExp(selector) + "[^>]*>([\\s\\S]*?)</" + escapeRegExp(selector) + ">";
```
See: https://github.com/Microsoft/TypeScript/issues/2803

fix(helper): backslash escaping (\s\S) in template strings are handled incorrectly

---

tsconfig.json

filename in `tsconfig.json` was misspelled.
Renamed: 
`"modules/universal/server/src/platform/xhr_node_impl.ts",` 
to:
`"modules/universal/server/src/platform/node_xhr_impl.ts",`

Fixing `gulp build`

---

modules/universal/server/src/render.ts

When no appRoot is given in the preboot options, the selector for the appcomponent to render is used as the appRoot for the clientscript for preboot.

feat: addded default appRoot selector from appComponent

---

modules/universal/server/src/platform/node_xhr_impl.ts

When trying to use templateUrl in component, server throws exceptions. That's because http method receives path string instead of json options and therefore hostname in request is undefined.

fix(universal): get method should take parsed options instead of string

---

modules/preboot/src/browser/listen/listen_by_event_bindings.ts

use a regex to match `(event)` and `on-event`:
```javascript
('(click)').match(/^(?:on-|\()([-\w]+)\)?$/).pop(); //=> click
('on-click').match(/^(?:on-|\()([-\w]+)\)?$/).pop(); //=> click
```

chore(preboot): use a regex to extract ng2 event names

---

modules/preboot/src/server/presets.ts
modules/preboot/test/server/presets_spec.ts

closes https://github.com/angular/universal/issues/245

chore(prereboot): replay 'input' and 'change' events during preboot

---

custom_typings/server.d.ts
modules/universal/mock.js
modules/universal/server/src/node/mock/window.ts

PR for https://github.com/angular/universal/issues/282

feat(window): mocking window object

---

package.json

Feature for:
Feature addition:
Automatic script for installing the entire project & external modules.
Starting with Preboot, then Universal, then it installs all other modules as well as typings.
Afterwards it even `npm installs` the Universal repo itself.
Useage:
When Repo is pulled down simply run `npm run install:all` and it will take care of the rest. (*note: takes ~10 minutes to install all the node modules & typings for all modules/ projects & repo itself*)
Afterwards a dev can do `npm start`, and voila - Universal is up and running.

feat(universal): Create install-all script

---

index.js

Typo just fixing path to index.ts file in examples/src

fix(universal): Fix server file path to index.js

---

modules/preboot/.gitignore
modules/preboot/package.json
modules/preboot/src/node/browser_code_generator.ts
modules/preboot/test/node/normalize_spec.ts
modules/preboot/typings.json

Added missing type definitions and fixed broken unit test.
Warnings when you do `gulp tsc`
Clean build and clean tests
No

fix(preboot): no more type warnings and fixed broken unit test

---

modules/preboot/package.json

- [*] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [*] preboot
Fixing of preboot installation
right now there are an exception on trying to clean install universal with preboot depency
```bash
npm ERR! preboot@2.0.7 preinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the preboot@2.0.7 preinstall script 'typings install'.
npm ERR! Make sure you have the …
```

fix(install): do not use globally installed typings in preinstall

---

modules/universal/src/node/platform/node_xhr_impl.ts

Adds DI annotation to originUrl parameter in node_xhr_impl to make it optional.
Parameter is required.
Parameter is optional
No
The parameter already defaults to an empty string if not specified,
so this fix makes the parameter completely optional.

fix(universal): make originUrl optional in node_xhr_impl

---

modules/broccoli-prerender/package.json
modules/broccoli-prerender/src/prerender.ts

Bug fix
Only includes `providers` from config, ignores `platformProviders`, causes DI errors.
Merges `providers` and `platformProviders` from config.
No

fix(broccoli-prerender): merge providers and platformProviders when serializing app

---

modules/broccoli-prerender/package.json
modules/express-engine/package.json
modules/grunt-prerender/package.json
modules/gulp-prerender/package.json
modules/hapi-engine/package.json
modules/polyfills/package.json
modules/preboot/package.json
modules/universal/package.json
modules/webpack-prerender/package.json

Closes #402 
change rm -rf to rimraf to prevent npm install fail on win env
See issue #402 
No

build: change rm -rf to rimraf to prevent npm install fail on win env

---

modules/preboot/package.json
modules/preboot/src/browser/dom.ts
modules/preboot/src/browser/preboot_browser.ts

Preboot onLoad handler called when document.readState === 'interactive' now which should be more accurate than the previous method.
Currently just looks for document.body to exist.
Now will check document.readState === 'interactive'
No

fix(preboot): better solution for document readyState

---

modules/universal/src/common/tokens/index.ts
modules/universal/src/node/http/node_http.ts

Related to issues: #273, and _https://github.com/aspnet/NodeServices/issues/66_
This is pretty easy fix, just to enable possibility to integrate server request cookie
Currently cookies not handled, just abstract class provided.
Provided abstract class injected as optional parameter to node_http, so we could grab cookie string from it. It provide abiliti to inject this cookie object from server. Here is some …

feat(universal-cookie): basic implementation of universal cookie

---

modules/universal/src/node/bootloader.ts

I couldn't exec `npm run test`...
```
$ node -v
v6.2.0
$ npm run test
> angular2-universal@0.0.1 test /Users/vvakame/Dropbox/work/ng-ssr-cli/angular2-universal
> gulp karma
(node:48562) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```
Bug fix.
We can't get code generation result with preboot by Bootloader#serializeApplication.
https://github.com/angular/universal/blob/805625d40e4b71d74159172506425e5002d4dbfa/modules/universal …

fix(universal): fix bootloader preboot config handling

---

modules/express-engine/src/engine.ts

Re-introduce the use of the reuseProviders option.
#421 
No
fix an issue where express-engine renders only first visited route if template doesn't change

fix(express-engine): fix route rendering if no template change (#421)

---

modules/universal/src/node/platform/dom/node_dom_renderer.ts

**Bug fix**
Checkboxes break when server rendered by Universal (because true/false is passed to them)
No longer breaks
**No**

bug(universal): Fix ng-template Checkbox issue

---

modules/express-engine/package.json
modules/hapi-engine/package.json
modules/universal/package.json

v `0.103` is pointing to older versions of express & hapi engines (*0.14.0*) which list angular2-universal `0.102` as a **peerDependency** causing install issues.
Upgraded to latest versions:
"angular2-express-engine": "^0.14.2",
"angular2-hapi-engine": "^0.14.2"
Should fix #447 
Also looks will fix the peerDependency CLI issue (https://github.com/angular/angular-cli/issues/958),
but not the underlying `index.html` being blank. (same issue here @ #445)

bug(Universal): Fix peerDependencies issue w/ v 0.103

---

modules/universal/src/browser/bootstrap.ts
modules/universal/src/browser/ng_preload_cache.ts
modules/universal/src/common/index.ts
modules/universal/src/common/utils.ts
modules/universal/src/node/directives/node_form.ts
modules/universal/src/node/http/node_http.ts
modules/universal/src/node/http/preload_cache.ts
modules/universal/src/node/platform/dom/node_dom_renderer.ts
modules/universal/src/node/platform/node.ts
modules/universal/src/node/platform/node_shared_styles_host.ts
modules/universal/src/node/platform/node_template_parser.ts
modules/universal/src/node/platform/node_xhr_impl.ts
modules/universal/src/node/render.ts
modules/universal/src/node/stringify_element.ts

This PR gets rid of many of the deep imports from Angular. For utility functions from Angular facade, I copied some of the useful ones into `universal/src/common/utilities.ts`. For simpler utility functions, I just inlined it.
This leaves just a few files that are using deep imports: 
* modules/universal/src/node/platform/node_template_parser.ts
* modules/universal/src/node/platform/node_template_parser-rc.0.ts
* modules/universal/src/node/platform/node.ts
_Most_ of what those modules are importing from deep paths is types that are just used for type information.

chore: replace private imports with copies of utility functions

---

modules/webpack-prerender/package.json
modules/webpack-prerender/src/prerender.ts

Update `webpack-prerender` to work with latest `angular2-universal`.
`webpack-prerender` doesn't work with latest `angular2-universal`.
`webpack-prerender` works with latest `angular2-universal`.
Yes. Users will need to change the `options` object sent to `angular2-webpack-prerender` to match `IWebpackPrerender`, see …

chore(webpack-prerender): update plugin and deps

---

package.json

Causes error when `npm i` since typings.json isn't here anymore.

bug(package): Remove typings from postinstall

---

DOCUMENTATION.md
README.md

Documentation & Migration Guide

---

modules/universal/src/browser/universal-module.ts
modules/universal/src/node/proxy-document.ts

Feature
preboot complete() is called immediately upon client bootstrap, wether you want it to be or not
Allows a configuration to override the automatic prebooting. This is especially useful is you have to do anything asynchronous before preboot complete runs, such as fetching data.
Usage is
```ts
imports: [
UniversalModule.withConfig({ autoPreboot: false }), // default behavior is still `true`
]
```
* **Does this PR introduce a breaking change?** (What …

feat(universal): Allow for configuring if preboot complete() is called automatically (immediatelly) or manually (asynchronously)

---

modules/platform-node/node-platform.ts

Fixes a memory leak
If you run servers in production, NgModules are generated per request and cached indefinitely, leading to a serious memory leak that will eventually floor your servers and you'll have to restart them constantly (up to every 15 minutes!)
Use WeakMap instead of Map to ensure if all references are lost to a cache key the value is garbage collected
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …

fix(platform-node): Remove memory leak

---

gulpfile.ts
package.json

Fixes #608
'ngc' is an unknown internal/external command. 
Cross-platform fix to get
Windows `gulp` working by running ngc command through npm scripts.

fix(gulpfile): ngc cross-platform fix

---

build-utils.ts
gulpfile.ts
modules/express-engine/src/index.ts
modules/grunt-prerender/tasks/prerender.ts
modules/gulp-prerender/src/prerender.ts
modules/hapi-engine/src/engine.ts
modules/platform-node/__private_imports__.ts
modules/platform-node/helper.ts
modules/platform-node/node-document.ts
modules/platform-node/node-http.ts
modules/platform-node/node-location.ts
modules/platform-node/node-platform.ts
modules/platform-node/node-renderer.ts
modules/platform-node/parse5.d.ts
modules/platform-node/tokens.ts
modules/universal/src/browser/universal-module.ts
modules/universal/src/common/index.ts
modules/universal/src/node/proxy-document.ts
modules/webpack-prerender/src/prerender.ts
tsconfig.json

improve ts files.
Now, angular2-platform-node (and preboot) are not compatible with --noImplicitAny options.
This is spread affect to user land tsconfig settings.
I want to use --noImplicitAny options in my project.
Users can't use --noImplicitAny with this package.
We can use --noImplicitAny with this package!
maybe no
* **Other …

refactor(universal): --noImplicitAny support

---

modules/universal-polyfills/package.json

* The need to manually require this module is part of the angular core documentation
Bug fix
#604 
No
Change the polyfills to include reflect-metadata as a peer dependancy. If two modules import different versions of this module it will cause some very confusing errors. By including it as a peer npm will output …

fix(polyfills): Remove reflect-metadata from the polyfills

---

.github/PULL_REQUEST_TEMPLATE.md
modules/ng-express-engine/README.md
modules/ng-express-engine/index.ts
modules/ng-express-engine/package.json
modules/ng-express-engine/src/main.ts
modules/ng-express-engine/src/tokens.ts
modules/ng-express-engine/tsconfig.json
package.json

feature
There is no express engine
There will be an express engine which allows server side rendering of Angular apps.
No

feat(ng-express-engine): add ng-express-engine

---

modules/ng-express-engine/README.md
modules/ng-express-engine/index.ts
modules/ng-express-engine/package.json
modules/ng-express-engine/tokens.ts
modules/ng-express-engine/tsconfig.json

Feature
Currently, importing the tokens from the main index will break client side so the user must import from @nguniversal/express-engine/dist/src/tokens
https://github.com/angular/universal/issues/703
Tokens should now be imported from @nguniversal/express-engine/tokens
Yes,
If a user …

build(ng-express-engine): introduce tokens entry

---

modules/ng-aspnetcore-engine/src/main.ts
modules/ng-aspnetcore-engine/tsconfig.json
modules/ng-express-engine/src/main.ts
modules/ng-express-engine/tsconfig.json
tsconfig.json

build / refactor
Currently everybody has their own tsconfig.
Everybody can extend their tsconfig off of a main one
Also applied stricter typescript checks
It should not

build(engines): extend tsconfigs off a base tsconfig

---

modules/ng-express-engine/README.md

- Fix up syntax error for options that are intended to be returned
- Change to take advantage of object shorthand
Fixing documentation of syntax errors
Currently the readme recommends using
```ts
(req: Request, res: Response) => {
req: req,
res: res
}
```
but this is a syntax error in Node.
No

docs(express): fix up return values

---

.travis.yml

- Add installation of C++11 standard compliant compiler to Travis CI build process
```
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
```
```
```
CI update
Travis CI posts a warning about building of native extensions - here is a sample snippet from a [build](https://travis-ci.org/angular/universal/jobs/241704388):
> Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems …

chore(ci): add c++11 standard compliant compiler

---

build.sh
modules/ng-module-map-ngfactory-loader/README.md
modules/ng-module-map-ngfactory-loader/index.ts
modules/ng-module-map-ngfactory-loader/package.json
modules/ng-module-map-ngfactory-loader/src/index.ts
modules/ng-module-map-ngfactory-loader/src/module-map-loader.module.ts
modules/ng-module-map-ngfactory-loader/src/module-map-ngfactory-loader.ts
modules/ng-module-map-ngfactory-loader/tsconfig.json
package.json

```
```
```
```
Feature
Currently, there is no such ngfactory loader
This introduces a ngfactory loader mainly used with the cli but basically loads modules based on a map
No

feat(ng-module-map-ngfactory-loader): introduce module-map-ngfactory loader

---

UPGRADE-GUIDE.md

`'@ng-universal/express-engine';` results in a failed import
Use `'@nguniversal/express-engine'` as the file path instead
> None
> Docs: typo fix
> Doc instructions result in a failed import
> successful import of `ngExpressEngine`
> No
> N/A

docs(UPGRADE-GUIDE) fix a typo in filepath

---

.gitignore
modules/ng-aspnetcore-engine/package.json
modules/ng-express-engine/package.json
modules/ng-module-map-ngfactory-loader/package.json
package.json
publish.sh
tsconfig.json

Also start publishing @nguniversal/module-map-ngfactory-loader for
handling lazy loaded modules on the server.
```
```
```
```

chore(release): version bump to 1.0.0-beta.3

---

build.sh

`build.sh` would not fail travis if a package did not build

fix(packaging): fail build.sh when a package does not build

---

modules/module-map-ngfactory-loader/src/module-map-loader.module.ts

- Changes return type of provideModuleMap to StaticProvider to
allow for compatibility with angular v5
```
```
```
```
Bug fix
Return type of provideModuleMap is Provider
Return type of provideModuleMap is StaticProvider
Since master requires angular v5, no breaking change. 
Should only be merged to the 5.x …

fix(module-loader): change type of provideModuleMap to StaticProvider

---

build.sh
modules/common/README.md
modules/common/index.ts
modules/common/package.json
modules/common/src/transfer_http.ts
modules/common/tsconfig.json
package.json

Add a TransferHttpCacheModule that when included in the App module will start caching Http requests on the server and transfer the cache to the client.
This will help avoid duplicate requests from the client for requests that the server application already made.

feat(common): add a common module with TransferHttpCacheModule

---

modules/hapi-engine/README.md

```
```
```
```
docs update
Some example code in hapi README are ill-formed; parenthesis is not balanced.
fix the example code by adding/removing parens

docs(hapi): fix parens in example code

---

modules/common/README.md

```
```
```
```
Docs update for TransferHttpCacheModule.
I couldn't get TransferHttpCacheModule to work by only installing it in my top-level App module, as the documentation suggests. 
Improved documentation. I had to do add two other steps for the module to work: import ServerTransferStateModule in Server module and wrap bootstrapModule call under an event listener. This blog post pointed me in the right direction: …

docs(universal): Expand TransferHttpCacheModule installation steps

---

karma.conf.js
modules/index.spec.ts
package.json
tsconfig.json
yarn.lock

feat(build): add unit testing with karma

---

modules/aspnetcore-engine/README.md
modules/aspnetcore-engine/src/interfaces/engine-options.ts
modules/aspnetcore-engine/src/main.ts
modules/express-engine/README.md
modules/express-engine/src/main.ts
modules/hapi-engine/README.md
modules/hapi-engine/src/main.ts

* Add url and document as optional parameters for rendering
* Add optional parameters setup to the README

feat(engines): add optional url and document to render options

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

condenses the info neeed in PR / Issue templates down to just what we actually need
Also makes it more readable

 docs: reduce uneeded info in issue/pr templates

---

modules/common/src/common-engine/engine.ts
modules/common/src/common-engine/interfaces.ts
modules/common/tokens/index.ts

- exports the private tokens from Common Engine
- exports less of the private api in Common Engine

refactor(common): reduce CommonEngine api

---

modules/common/src/common-engine/file-loader.ts

* this causes issues with bundling, and is not needed since the export is already "private"

fix(common): remove internal monicker for FileLoader

---

modules/common/engine/private_api.ts
modules/common/private_api.ts
modules/common/spec/transfer_http.spec.ts
modules/common/src/transfer_http.ts

Based on the work in https://github.com/angular/universal/pull/987
What kind of change does this PR introduce?
```
[x] Feature
```
TransferHttpCache does not respect url params  
Issue Number: https://github.com/angular/universal/issues/927
Now respects params 
```
[x] Yes
[ ] No
```
Technically this is a breaking change since 
before:
/my/url?key=value
/my/url
Both of these would override each others values in the cache
But now they'd have their own cache

feat(common): TransferHttpCache now respects url params

---

.circleci/config.yml
.github/CODEOWNERS

* the default allocation is not enough for Bazel to perform the build it needs

ci: increase resources for testing

---

README.md

Fix link to `module-map-ngfactory-loader`  from README.md

docs: Fix link to module-map-ngfactory-loader

---

modules/express-engine/schematics/README.md
modules/express-engine/schematics/install/files/root/__serverFileName@stripTsExtension__.ts
modules/express-engine/schematics/install/index.ts

* Contains fixes for Express engine
schematics

fix(express-engine): add server configuration to schematics

---

modules/common/src/state-transfer-initializer/module.ts

If `DOMContentLoaded` event already fired and after adding a listener for `DOMContentLoaded` event, then it will not execute.
So added a check to resolve() the promise if DOMContentLoaded event already fired.

Is not working if DOMContentLoaded already fired

---

modules/aspnetcore-engine/src/main.ts
modules/express-engine/src/main.ts
modules/hapi-engine/src/main.ts

* Add the absolute URL to view generation to allow for access through
the document's native location object
* Future PR will allow user to override the default url
NOTE: This will act as a precursor to correct absolute path resolution for `HttpClient`

feat(modules): pass in absolute URL as default for view rendering

---

modules/express-engine/schematics/install/index.spec.ts
modules/express-engine/schematics/install/index.ts
modules/express-engine/schematics/install/utils.ts

feat(express-engine): add ModuleMapLoaderModule to the app server imports during ng-add

---

modules/express-engine/BUILD.bazel
modules/express-engine/spec/index.spec.ts
modules/express-engine/testing/mock.server.module.ts
modules/hapi-engine/BUILD.bazel
modules/hapi-engine/spec/index.spec.ts
modules/hapi-engine/testing/example.ts
modules/socket-engine/BUILD.bazel
modules/socket-engine/spec/index.spec.ts
modules/socket-engine/src/main.ts
modules/socket-engine/testing/mock.server.module.ts

Unit tests can run again with dependency on @angular/http removed.
Needed to convert the tests to use AOT-ed factory instead of relying on
JIT because that no longer works with Bazel and using Angular packages
from npm instead of compiling from source.

test: re-enable unit tests

---

modules/express-engine/schematics/install/index.spec.ts
modules/express-engine/schematics/install/index.ts
modules/hapi-engine/schematics/install/index.spec.ts
modules/hapi-engine/schematics/install/index.ts

This fixes a couple of regressions in the latest version. Were running `ng add` would cause configuration from the browser builder to be deleted instead of updated
Fixes #1189

fix(schematics): ng add removes options from browser builder

---

modules/express-engine/schematics/testing/test-app.ts
modules/hapi-engine/schematics/testing/test-app.ts

Under bazel require.resolve is patched and we should use it to resolve runfile artifacts so that tests can run on platforms were bazel will not create symlinks such as Windows

build: under bazel runfiles symlinks are not created in windows

---

.circleci/bazel.rc

When a tests fails in CI it will be useful that failures are disabled in CI as not all users have SSH access.
Also this adds `flaky_test_attempts` to 2 as this morning I noticed a flake on a tests which failed but passed when force pushing

build: enable verbose_failures for CI

---

integration/express-engine-ivy/server.ts
integration/express-engine-ve/server.ts
modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts

Change the schematics to export the Express app object itself from
server.ts.
This can be used from a serverless function to call into the Express app
directly. Example -
https://github.com/angular/angularfire2/blob/master/docs/universal/cloud-functions.md

fix(express-engine): export Express app from server.ts

---

integration/express-engine-ivy/server.ts
integration/express-engine-ve/server.ts
integration/hapi-engine-ivy/server.ts
integration/hapi-engine-ve/server.ts
modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
modules/hapi-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts

Export Hapi and Express app from the server bundle so that they can be
referenced in serverless functions if needed.

fix(hapi-engine, express-engine): export app for serverless functions

---

integration/express-engine-ivy/server.ts
integration/express-engine-ve/server.ts
modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts

This avoids Angular route match failures when the Express engine is
mounted on a different URL (Happens with Firebase and other serverless
setup).

fix(express-engine): set APP_BASE_HREF to req.baseUrl

---

integration/run_tests.sh

At the moment, the integration tests CI tasks is full of install logs which are noisy and hide "more" import logs

ci: add `--silent` to yarn install

---

modules/express-engine/schematics/install/schema.json
modules/hapi-engine/schematics/install/schema.json

feat(express-engine): support `ng-add` without specifying `clientProject`
When unset we set the clientProject to the resolved packageName from the current working directory
Users can now use the schematic via:
```
ng add @nguniversal/express-engine
```
feat(hapi-engine): support `ng-add` without specifying `clientProject`
When unset we set the clientProject to the resolved packageName from the current working directory
Users can now use the schematic via:
```
ng add @nguniversal/hapi-engine
```

support `ng-add` without specifying `clientProject`

---

modules/common/schematics/add/index.spec.ts
modules/common/schematics/add/index.ts

The server target main option needs to be updated when running the add schematic to point to the server.ts entrypoint

fix(common): update server main option when using `ng add/ng update`

---

.circleci/config.yml

With this change we should get more cache hit rates since previously all PRs had a different cache key

ci: update key cache to have more cache hits

---

modules/common/schematics/add/index.ts
modules/express-engine/schematics/install/index.spec.ts
modules/hapi-engine/schematics/install/index.spec.ts

At the moment, we run `npm install` twice if the current project doesn't have a server target because we run 1 in our respective engine schematics, ex: https://github.com/angular/universal/blob/e4f078133c14fcb602baaabf8c277ff003d137f5/modules/hapi-engine/schematics/install/index.ts#L35-L37 and other in the external universal schematics.
With this change we disable the install in the external universal schematic and rely on install task in our code.

fix(common): always pass `skipInstall` to `universal` schematic

---

integration/express-engine-ivy/angular.json
integration/express-engine-ivy/package.json
integration/express-engine-ve/angular.json
integration/express-engine-ve/package.json
integration/hapi-engine-ivy/angular.json
integration/hapi-engine-ivy/package.json
integration/hapi-engine-ve/angular.json
integration/hapi-engine-ve/package.json
modules/builders/BUILD.bazel
modules/builders/src/ssr-dev-server/index.ts

The ssr-dev-server builder starts the browser builder and the server builder in watch mode.
To show how it works, one can run the serve:ssr-dev-server npm script in the express-engine-ivy integration test project

feat(builders): implement ssr-dev-server

---

modules/common/schematics/BUILD.bazel
modules/common/schematics/testing/test-app.ts
modules/express-engine/schematics/BUILD.bazel
modules/express-engine/schematics/testing/test-app.ts
modules/hapi-engine/schematics/BUILD.bazel
modules/hapi-engine/schematics/testing/test-app.ts

Currently we are including the testing folder in the npm_package

build: exclude schematics `testing` folder from being shipped

---

modules/builders/BUILD.bazel
modules/builders/builders.json
modules/builders/src/index.ts
modules/builders/src/prerender/index.spec.ts
modules/builders/src/prerender/index.ts
modules/builders/src/prerender/schema.json
modules/builders/src/prerender/schema.ts

The prerender builder starts the browser builder and the server builder. It then uses the server bundle to render an array of routes and writes the rendered html to
`[browser builder output path(s)]/[route]/index.html`.

feat(builders): implement prerender

---

modules/common/schematics/add/index.spec.ts
modules/common/schematics/add/index.ts

Rename the npm target `serve:ssr:dev` to just `dev:ssr`

fix(common): use shorter name to start the ssr-dev-server

---

modules/common/schematics/add/index.spec.ts
modules/common/schematics/add/index.ts

Automatically set up prerender builder with `ng add @nguniversal/express-engine`.

feat(prerender): config preredner in ng add

---

modules/common/schematics/add/index.ts

This can help the firebase deploy builder(for instance) to call the either the browser build or prerender target uniformly with configuration set to production.

fix(common): add production config section to prerender builder config

---

.circleci/config.yml

With this change we introduce a couple of changes
- Do `yarn install` and code checkout once in the setup phase
- Save cache in `build-packages-dist` to ensure that we cache Bazel action outputs at the very end of our builds so that we will later get better cache hit rate
- We use circle ci 2.1 features such as action executors and commands
- Removed the `bazel-lint` task which was redundant
- We save yarn cache to circli ci cache instead of node_modules directory
- Use a cache key fallback, so to use the last cached version when a dependency is updated.

ci: improve circle ci setup

---

modules/builders/BUILD.bazel
modules/builders/package.json
modules/builders/src/prerender/index.spec.ts
modules/builders/src/prerender/index.ts
modules/builders/src/prerender/models.ts
modules/builders/src/prerender/schema.json
modules/builders/src/prerender/schema.ts
modules/builders/src/prerender/utils.spec.ts
modules/builders/src/prerender/utils.ts
package.json
yarn.lock

- Added dependency for guess-parser. See https://www.npmjs.com/package/guess-parser for details.
- Added boolean `guessRoutes` to prerender options schema.
- Extract routes using `guess-parser` if `guessRoutes` is set to true.
- Added an integration test to `prerender/index.spec.ts`.
- Added a unit test to `prerender/utils.spec.ts`

feat(builders): extract routes with guess-js

---

integration/express-engine-ivy-prerender/server.ts
integration/express-engine-ivy/server.ts
integration/express-engine-ve/server.ts
integration/hapi-engine-ivy/server.ts
integration/hapi-engine-ve/server.ts
modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
modules/hapi-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts

The problem is that the `interceptor.js` which is used by IIS Node will require the application files rather than executing it. https://github.com/tjanczuk/iisnode/blob/8657944f8803d84514c0c7ddd48c046aa68e6edf/src/scripts/interceptor.js#L210
Thus, the server `run` method will never get invoked.

schematics compatible with IIS Node and Azure App service

---

integration/hapi-engine-ivy/package.json
integration/hapi-engine-ivy/tsconfig.json
integration/hapi-engine-ve/package.json
integration/hapi-engine-ve/tsconfig.json
modules/common/schematics/add/index.spec.ts
modules/hapi-engine/schematics/install/index.ts
package.json
yarn.lock

`@types/hapi__iron`, `@types/hapi__boom` are transitive deps of `@types/hapi__hapi` and is deprecated as these provides their own types definitions however we don't use the latest version so we need to add the resolutions.

build: update to version

---

modules/builders/src/ssr-dev-server/index.spec.ts
modules/builders/src/ssr-dev-server/index.ts

fix(builders): send `X-Forwarded` headers when using ssr-dev-server

---

modules/builders/src/prerender/utils.ts

fix(builders): default to a minimum of 1 CPU when sharding builds

---

modules/builders/src/ssr-dev-server/index.spec.ts

While this works locally, on ci this is causing 90% of our builds to be red,.

test: disable flaky ci test

---

.bazelrc

`--symlink_prefix=/` will not generate `bazel-out` in the repository,
which would cause the npm_package.publish script to fail, since it looks
for the `bazel-out` directory to find package directory and package.json

build: Change --symlink_prefix to dist/

---

modules/aspnetcore-engine/package.json
modules/builders/package.json
modules/common/package.json
modules/express-engine/package.json
modules/hapi-engine/package.json
modules/socket-engine/package.json

By default if no `packageGroupName` is provided `ng-update` will use the first item in `packageGroup` which in this case it is always `@nguniversal/aspnetcore-engine`.
With this change we set the `packageGroupName` of each package, also we remove `ng-update` from `@nguniversal/builders` as this gets updated when running `ng update` on `@nguniversal/express-engine`  or `@nguniversal/hapi-engine`.
Closes #1542 and closes #1533

fix: ng update showing packages that do not exist in my package

---

.circleci/config.yml

While having a cache key fallback can be beneficial it also results in increased cache size the currently the cache size almost doubled in size to 2.6Gib because it is never cleaned and results in slower builds.

ci: remove cache key fallback

---

modules/builders/src/ssr-dev-server/index.ts
modules/builders/src/ssr-dev-server/schema.json

Wiith this change we add the ability to inspect the server code when running the ssr-dev-server. We launch the development server in inspector mode on address and port `127.0.0.1:9229`.
Note: the debugger will need to be attached on every incremental build, since the Node process is restarted each time.
Closes #1624

feat(builders): add `--inspect` option to `ssr-dev-server` builder

---

package.json
yarn.lock

@bazel/bazel  is being deprecated. @bazel/bazelisk is a drop in
replacement for @bazel/bazel.

build: use @bazel/bazelisk rather than @bazel/bazel

---

modules/express-engine/spec/index.spec.ts
modules/express-engine/src/main.ts
modules/express-engine/testing/mock.server.module.ts

The default implementation of the Express server does not pass the `res` render option to the engine. In this case, fallback to use the response stored in Express' request object.
Closes #1691

fix(express-engine): use response in request object if not provided

---

modules/express-engine/tokens/BUILD.bazel
modules/express-engine/tokens/injection-tokens.ts
package.json
yarn.lock

@types/express-serve-static-core is now a direct dependency of
@types/express, and having both creates TypeScript conflicts.

build: remove dev dependency on @types/express-serve-static-core

---

tools/defaults.bzl

When tslib is listed as part of the globals, it will not be embedded in the UMD bundles.
https://github.com/angular/angular/blob/fd65958b887f6ea8dd5235e6de1d533e4c578602/packages/bazel/src/ng_package/ng_package.bzl#L226-L228
Users using UMD bundles, shouldn't be needing to add the tslib script, also this is important because tslib is a direct depedency of the package and not a peer depedency.
This is also to align with the Angular FW packages.

build: embed tslib in umd bundles

---

tools/tslint-rules/noRxjsPatchImportsRule.ts

Remove usage of the term whitelist in commenting for noRxjsPatchImportsRule

build: update tslint rules to remove usage of whitelist in comments

---

.github/workflows/lock-closed.yml

Update to the latest lock-closed action to fix the link which is used.

ci: bump to lastest sha of angular/dev-infra's lock-closed action

---

modules/builders/BUILD.bazel
modules/builders/package.json
modules/builders/src/prerender/index.ts
modules/builders/src/prerender/render.ts
package.json
yarn.lock

With this change we improve the prerender logging by:
- Reduce the verbosity of the logs when generating route
- Improve logs when an error occuries
- Add a spinner
Closes #1844

fix(builders): improve prerendering logging

---

integration/express-engine-ivy-prerender/angular.json
integration/express-engine-ivy/angular.json
integration/express-engine-ve/angular.json
integration/hapi-engine-ivy/angular.json
integration/hapi-engine-ve/angular.json
modules/builders/src/ssr-dev-server/index.ts
modules/builders/testing/hello-world-app/angular.json

As of Angular CLI version 11, extractCss is deprecated and is now done by default.

fix: remove extractCss from ssr-dev-server builder

---

modules/hapi-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts

Right now when you generate a Angular CLI project and then add the hapi-engine and run it like
```
$ ng add @nguniversal/hapi-engine
$ ng run ngssr:serve-ssr
```
it fails due to a TS error.
Issue Number: N/A
Fixes the schematic by solving the TS error
```
[ ] Yes
[x] No
```

fix(hapi-engine): ng-add schematic

---

.github/workflows/lock-closed.yml

Please read https://github.com/angular/dev-infra/pull/82#issuecomment-758198930.
CC @gkalpak

fix the warning on lock-closed gh-actions: Warning: Unexpected input(s) 'lock-bot-key'

---

modules/aspnetcore-engine/package.json
modules/builders/package.json
modules/common/package.json
modules/express-engine/package.json
modules/hapi-engine/package.json
modules/socket-engine/package.json
package.json
renovate.json

BREAKING CHANGE:
Node.js version 10 will become EOL on 2021-04-30.
Angular CLI 12 will require Node.js 12.13+ or 14.15+. Node.js 12.13 and 14.15 are the first LTS releases for their respective majors.

build: set minimum Node.js version to 12.13

---

modules/builders/src/ssr-dev-server/index.spec.ts
modules/builders/src/ssr-dev-server/index.ts
modules/builders/src/ssr-dev-server/schema.json
modules/builders/src/ssr-dev-server/schema.ts

With this change we add SSL support to the SSR dev-server. We expose 3 new options;
- `ssl`: Turn on/off HTTPs
- `sslKey`: SSL key to use for serving HTTPS
- `sslCert`: SSL certificate to use for serving HTTPS
Closes #1633

feat(@nguniversal/builders) add SSL support for dev-server

---

modules/builders/src/prerender/index.ts
modules/common/engine/src/inline-css-processor.ts

When critical font rules are not inlined it will cause blinking as during first render the fallback font will be rendered.
Closes #2002

fix(@nguniversal/common): inline critical font-face rules when using critical css inlining

---

renovate.json

This eliminates the requirement that when master is not a major we require to change the label.  `target: minor` is always get merged into master (and master only): https://github.com/angular/angular/blob/ed77bfea26e64bd24019812131e14f5dd450fcf5/docs/BRANCHES.md#pull-request-examples  hence using `target: major` is not needed in this case.

ci: change renovate label to `target: minor`

---

modules/express-engine/schematics/install/schema.json

In Angular CLI version 12, JSON Schema draft-04 will no longer be supported. Therefore id will need to be updated to $id.
We replace id with $id, this no longer valid in draft-07.
Replace all $schemas to http://json-schema.org/draft-07/schema, this is needed to "pin" the schema to draft-07.
More information about this draft can be found https://json-schema.org/draft-07/json-schema-release-notes.html

refactor: update `$schema` and `id` keywords

---

modules/builders/src/ssr-dev-server/index.spec.ts
modules/builders/src/ssr-dev-server/index.ts
modules/builders/src/ssr-dev-server/schema.json
modules/builders/src/ssr-dev-server/schema.ts
tools/defaults.bzl

With this change we added a new `proxyConfig` option to be used to provide custom proxy configurations to the ssr-dev-server builder.
Closes #1757

feat(@nguniversal/builders): add support for proxy configuration in ssr-dev-server

---

renovate.json

Renovate creates better commit message.

ci: remove `commitMessage` from Renovate configuration

---

modules/common/clover/server/src/server-engine.ts
modules/common/clover/server/src/stubs.ts

fix(@nguniversal/common): add Window stubs to Engine (Clover)

---

modules/express-engine/schematics/install/index.ts

Add `serverTarget` for the prerender architect in the add schematic
Closes #2120

fix(common): add `serverTarget` for prerender

---

modules/express-engine/schematics/install/index.ts

Use the `projectName` variable in the prerender architect.
I used the `projectName` variable to be consistent with the `ssr-dev-server` architect.

refactor(express-engine): use `projectName` for prerender

---

README.md

---
name: ⚙ Improvement
about: You have made an improvement to Angular Universal
---
There is no link to the contributing guidelines in the README.
I think it would be better to have a link to the Contributing guidelines in the README, just like in other Angular Organization repositories.
There is a link to the contributing guidelines in the README.
```
[ ] Yes
[x] No
```

docs: add a link of the contributing guidelines to README

---

integration/clover/src/app/app.module.ts
integration/clover/src/app/homepage.component.ts
integration/clover/src/assets/data.json
integration/clover/test.js
modules/builders/BUILD.bazel
modules/builders/package.json
modules/builders/src/static-generator/index.ts
modules/builders/src/static-generator/worker.ts

Using express to spawn a local static server for browser build artifacts which allows HTTP requests to a relative path like `/assets/data.json` while rendering.
Close #2132 
cc/ @alan-agius4

feat(@nguniversal/builders): spawn static server for build artifacts

---

package.json

Now that `12.1.0` has been released, the next prerelease is `12.2.0-next.0`.
I tried to do this via a direct push as expected in the [release doc](https://github.com/angular/universal/blob/4f9c6bafbfeeef17a3f66c5952135d9514c62dea/docs/process/release.md), but apparently `master` is a protected branch and refuses any update without a review. Might also want to update the doc?

build: update version to `12.2.0-next.0`

---

.ng-dev/config.ts
.ng-dev/release.ts
CHANGELOG.md
docs/process/release.md

This is to align the release process with that of Angular CLI repo.
NB: `yarn release publish` is still not yet configured.

build: update release notes to be generated using ng-dev

---

modules/builders/src/prerender/worker.ts

I have found (what i think it is) a small bug when prerendering multiples routes:
The **render** function on the worker will backup browserIndexOutputPath to _index.original.html_ when prerender.
But that **render** function will read (always) index.html (workerArgs.indexFile), whenever it is rendering a new route.
I have found a strange behaviour when prerendering a large number of routes (or using "numProcesses": 1), since render will be using the already pre-rendered html.
For example it will generate a duplicated (and diferent depending on the routes) app-state json script tag.
A quick workaround is prerendering the route "/",  the last of the routes, but I find checking on "index.original.html" a much better approach.

fix(@nguniversal/builders): index.original.html should be used if exists

---

modules/common/clover/server/src/server-engine.ts
modules/common/engine/src/engine.ts

With this change we disable critical css inline by default. The main motivations are the following issues https://github.com/angular/angular-cli/issues/20760 and https://github.com/angular/angular-cli/issues/20864.
BREAKING CHANGE:
Inlining of critical CSS is no longer enable by default. Users already on Angular version 12 and have not opted-out from using this feature are encouraged to opt-in using the `inlineCriticalCss` option.
The motivation behind this change is that the package used to parse the CSS has a number of defects which can lead to unactionable error messages when updating to Angular 13 from versions priors to 12. Such errors can be seen in the following issue https://github.com/angular/angular-cli/issues/20760.

feat(@nguniversal/common): disable critical CSS inlining by default

---

integration/common-engine/src/main.server.ts
integration/express-engine-ivy-hybrid/src/main.server.ts
integration/express-engine-ivy/src/main.server.ts
integration/hapi-engine-ivy/src/main.server.ts
modules/aspnetcore-engine/package.json
modules/builders/BUILD.bazel
modules/builders/src/prerender/index.spec.ts
modules/builders/src/prerender/utils.spec.ts
modules/builders/testing/hello-world-app/angular.json
modules/builders/testing/hello-world-app/server.ts
modules/builders/testing/hello-world-app/src/main.server.ts
package.json
yarn.lock

With this change we re-enable the builders unit tests. We had to delete some utils specs since they were not written in a way to works with TypeScripts' esModuleInterop which causes exports to be read only.

test: re-enable builders tests

---

docs/process/release.md

This uses `yarn -s` to strip unnecessary wrapper text and uses `--type` instead of `--mode`, which is the required flag for `ng-dev`. The instructions now call out that two different release notes need to be generated in two different places.

docs: update release changelog generation process.

---

CHANGELOG.md

Also adds `12.1.2` and `12.1.3` release notes which apparently got missed previously. They should align with the existing GitHub releases.
/cc @alan-agius4 for sanity check, but due to timezone differences we'll merge this ASAP and just any issues afterwards.

docs: update `CHANGELOG` for `v13.0.0`

---

modules/express-engine/schematics/utils/utils.ts

According to the [document](https://angular.io/api/router/InitialNavigation#description), `initialNavigation: 'enabled'` have been deprecated.
It should be `initialNavigation: 'enabledBlocking'` now.

fix(@nguniversal/express-engine): initialNavigation should be 'enabledBlocking'

---

integration/clover/src/app/app-routing.module.ts
integration/clover/src/app/lazy/lazy-routing.module.ts
integration/clover/src/app/lazy/lazy.component.html
integration/clover/src/app/lazy/lazy.component.spec.ts
integration/clover/src/app/lazy/lazy.component.ts
integration/clover/src/app/lazy/lazy.module.ts
integration/clover/test.js
modules/common/clover/server/src/custom-resource-loader.ts

JSDom doesn't support script with `type=module` therefore we need to strip out this from the runtime.js.
Closes #2433

fix(@nguniversal/common): correctly handle lazy loaded routes in Clover

---

docs/process/release.md

Release tooling was updated in #2447 to use dev-infra's unified system. The actual documentation was mostly copied from the existing [Angular CLI release docs](https://github.com/angular/angular-cli/blob/e0a1a94e79a3b0a5ec03bb41c70e8f8674557c10/docs/process/release.md), with the key difference being that releases and published as necessary rather than every week.

docs: update release docs to reflect new tooling

---

modules/common/schematics/BUILD.bazel
modules/common/schematics/ng-add/files/src/server.ts.template
modules/common/schematics/package.json
modules/express-engine/schematics/BUILD.bazel
modules/express-engine/schematics/package.json

Migrations are currently published as CommonJS and also not bundled. Schematics, of which migrations are a type, are currently required to be CommonJS modules due to the Schematics Runtime not yet supporting ESM-based schematics.
closes #2491

Ensure CommonJS migrations can be accessed

---

modules/builders/README.md

A start for documentation about the universal builders. 
Better then WIP I would say, for now. Maybe it gives some overview about how the docs could look like.

docs(@nguniversal/builders): Added Builder Readme Overview

---

modules/builders/package.json
modules/common/package.json
modules/express-engine/package.json
package.json
yarn.lock

Node.js v12 will become EOL on 2022-04-30. As a result, Angular CLI v14 will no longer support Node.js v12.
BREAKING CHANGE:
Support for Node.js v12 has been removed as it will become EOL on 2022-04-30. Please use Node.js v14.15 or later.

feat(@nguniversal/common): drop support for Node.js 12

---

modules/express-engine/src/main.ts

The `originalUrl` as part of the request is meant to be immutable,
but some users may want the URL to be mutated by middleware. By
locking our URL construction to the originalUrl, we rob users of
this ability. Therefore, we construct the URL using comparable
elements of the request object.
Fixes #2564

fix(express-engine): construct req url instead of using originalUrl

---

.github/workflows/dev-infra.yml
.github/workflows/lock-closed.yml
.github/workflows/scorecard.yml

The currently recommended best practice for Github action workflows is to set top-level permissions to read only. And if the job uses the automatic `GITHUB_TOKEN`, fine-grained permissions for each job based on the job's requirements should also be added.
All existing workflows in the repository now have top-level read only permission blocks.
Only the `scorecard` workflow currently requires additional job level permissions and the minimum set of permissions were already present for the job.

ci: fix permissions and tags

---

package.json

This allows the `ng-dev` tool to accept the `13.1.x` branch as a minor release which doesn't conflict with `master`.
Trying to release currently fails with:
```
$ yarn -s ng-dev release publish
Error: Discovered unexpected version-branch "13.1.x" for a release-train that is already active in the "master" branch. Please either delete the branch if created by accident, or update the version in the next branch (master).
at findActiveReleaseTrainsFromVersionBranches (/home/douglasparker/Source/universal/ng-dev/release/versioning/active-release-trains.ts:137:13)
at fetchActiveReleaseTrains (/home/douglasparker/Source/universal/ng-dev/release/versioning/active-release-trains.ts:80:44)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ReleaseTool.run …
```

refactor: update `master` branch to `13.2.0-next.0`

---

.circleci/config.yml
.github/workflows/scorecard.yml
.ng-dev/github.ts
renovate.json

Changes from the `DIRECT` phase of the renaming master
to main planning doc.
Note: Skipping LTS backports here since we don't make any guarantees for the universal repo
and its likely not worth (we would need more ng-dev backports there as well)

build: changes for primary branch rename

---

package.json

`ng-dev` tool doesn't give the feature freeze option, most likely because the main branch is still set to 13.2.0 as the next release. This will switch it to 14 so the `ng-dev` tool supports feature freezing.

build: bumps version of `main` branch to `14.0.0-next.0` so the next release will be v14, not v13.2

---

modules/common/clover/server/src/custom-resource-loader.ts
modules/common/clover/server/src/server-engine.ts

---
name: ⚙ fix
about: [correctly handle headers for jsdom in Clover
---
the server agent is not working in angular. it just default fallback of jsdom
the user agent is not corect ly handle by Clover, we should make it correct.
Right now the userAgent is passing in jsdom options which is not correct. We should move it to customResourceLoader  
the user agent handle correctly as jsdom suggestion. Move userAgent to ResouceLoader as document
after modification, the userAgent work correctly
we just update it as the document
```
[ ] Yes
[x] No
```
I'm runing Clover on production app on https://awread.vn. I tested this change on my production and it work very good. I love this engine so much. Thanks for your effort

fix(@nguniversal/common): correctly handle headers for jsdom in Clover

---

package.json
yarn.lock

`ts-node` spawns a custom node launcher script and has a brotli-base64
encoded configuration that will point to the user-provided entry-point.
This breaks child process forking as we wouldn't be able to specify our
custom build worker and basically `ng-dev` would run inside `ng-dev`
again.

build: avoid use of ts-node wrapper script as it breaks child process forking

---

CONTRIBUTING.md

Updates the contributing guide to reflect the branch name of `code-of-conduct` repository

build: update contributing guide to reflect branch name of `code-of-conduct` repository

---

modules/common/clover/src/styles_host.ts

I've updated the check for `ngDevMode` since `!== undefined` will always return true even tho it's not explicitly provided by Terser.

fix(@nguniversal/common): handle `ngDevMode` correctly

---

CHANGELOG.md

Cherry-picks the changelog from the "14.0.x" branch to the next branch (main).

docs: release notes for the v14.0.3 release

---

modules/common/clover/src/transfer-http-cache/transfer-http-cache.interceptor.ts
modules/common/spec/transfer_http.spec.ts
modules/common/src/transfer_http.ts

This commit add support to handle responses  of types `arraybuffer` and `blob` in `TransferHttpCacheModule`.
Closes #2734

feat(@nguniversal/common): add support for `blob` and `arraybuffer` in `TransferHttpCacheModule`

---

modules/common/clover/server/src/server-engine.ts

`tough-cookie` which is a dependency of JSDOM did a breaking change in version 4.1 which requires special handling for cookies in localhost.
See: https://github.com/salesforce/tough-cookie/issues/246

fix(@nguniversal/common): handle cookies with localhost domain as path

---

modules/express-engine/schematics/install/schema.json
modules/express-engine/schematics/install/schema.ts

This option is no longer used by the universal schematic.
Fixes #2779

fix(@nguniversal/express-engine): remove default value of `appDir` option

---

CHANGELOG.md
package.json

The previous "next" release-train has moved into the release-candidate phase. This PR updates the next branch to the subsequent release-train.
Also this PR cherry-picks the changelog for v14.2.0-rc.0 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v14.3.0-next.0".

---

modules/builders/src/ssr-dev-server/index.ts

Note: this requires Node.js 18.10 or later due to https://github.com/nodejs/node/issues/44654
Closes #2813

feat(@nguniversal/builders): add sourcemap mapping support for dev-server

---

.bazelignore
.circleci/config.yml
.gitignore
BUILD.bazel
WORKSPACE
integration/clover/BUILD.bazel
integration/clover/test.sh
integration/common-engine/BUILD.bazel
integration/common-engine/e2e/protractor.conf.js
integration/common-engine/test.sh
integration/express-engine-ivy-hybrid/BUILD.bazel
integration/express-engine-ivy-hybrid/e2e/protractor.conf.js
integration/express-engine-ivy-hybrid/test.sh
integration/express-engine-ivy/BUILD.bazel
integration/express-engine-ivy/e2e/protractor.conf.js
integration/express-engine-ivy/test.sh
modules/builders/BUILD.bazel
modules/common/BUILD.bazel
modules/express-engine/BUILD.bazel
package.json
yarn.lock

Integration tests passing locally and on CI.
```
//integration/clover:test                                                PASSED in 84.4s
//integration/common-engine:test                                         PASSED in 147.5s
//integration/express-engine-ivy:test                                    PASSED in 165.1s
//integration/express-engine-ivy-hybrid:test                             PASSED in 172.3s
//modules/builders:unit_test                                             PASSED in 247.9s
//modules/common:unit_test                                               PASSED in 0.8s
//modules/common/schematics:unit_tests                                   PASSED in 3.7s
//modules/express-engine:unit_test                                       PASSED in 1.5s …
```

build: run integration tests with bazel

---

.circleci/config.yml

These tests are now ran as part of the build step through bazel.

ci: remove integration tests from seperate step

---

.ng-dev/commit-message.mts
.ng-dev/format.mts
.ng-dev/github.mts
.ng-dev/pull-request.mts
.ng-dev/release.mts
package.json
yarn.lock

Update all imports and remove no longer supported options.

build: replace `@angular/dev-infra-private` with `@angular/ng-dev`

---

modules/builders/src/prerender/index.ts
modules/builders/src/prerender/worker.ts
modules/builders/testing/hello-world-app/src/main.server.ts

In some cases, zone.js might not be part of the bundle, which cause zone async task not be patched and awaited correctly prior of rendering.

fix(@nguniversal/builders): import `zone.js` in worker during prerendering

---

modules/builders/BUILD.bazel
modules/builders/src/prerender/worker.ts

Prerendering does not work when using Node.js versions that contain the following commit https://github.com/nodejs/node/pull/43728 due to `loadesm` is now using `SafePromiseAll` which is not handled properly by zone.js.

fix(@nguniversal/builders): address method Promise.prototype.then called on incompatible receiver error

---

modules/common/engine/src/engine.ts
modules/express-engine/src/main.ts

This option is not required in the common engine.
Closes: #2893

fix(@nguniversal/common): mark `bootstrap` in `RenderOptions` as non required

---

CHANGELOG.md

Cherry-picks the changelog from the "15.0.x" branch to the next branch (main).

docs: release notes for the v15.0.0-rc.0 release

---

modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts

Add spacing to match other file generated by the Angular CLI

fix(@nguniversal/express-engine): fix formatting in generated `server.ts`

---

modules/builders/BUILD.bazel
modules/builders/src/prerender/index.ts
modules/builders/src/prerender/worker.ts

This is a fix for `Node > 16.17.1: Method Promise.prototype.then called on incompatible receiver` when using `@angular/localize`.

fix(@nguniversal/builders): Initialize zone.js once in rendering workers

---

.github/workflows/scorecard.yml

The scorecard action was failing for months. After looking into it, turns out the permissions were incorrectly set up and the signing failed because no id token was accessible..

build: fix scorecard action failing

---

.github/workflows/scorecard.yml

First of all, scorecard does not print a useful error at all. Looking through issues and their verify workflow logic, it seems like the permissions for the scorecard action workflow *need* to be set on the actual job itself, while the workflow-level permissions *cannot* contain any `write` permissions.
We already got further with the errors by enabling id-token write properly, but now the signing fails with an unknown error that we attempt to fix using this commit.

build: fix scorecard action signing

---

.circleci/config.yml

This addresses an issue with causes Chrome installation to fail with the below errors
```
Google Chrome is not currently installed; installing it
Exited with code exit status 1
```

ci: update `circleci/browser-tools` to `1.4.0`

---

modules/builders/package.json
modules/common/package.json
modules/express-engine/package.json
tools/defaults.bzl

This is so that version updates are managed by renovate bot.

build: remove `defaults.bzl` version in favor of version in `package.json`

---

renovate.json

This package contains changes which are no longer compatible with this repo and also require upstream changes.
See: https://github.com/angular/angular/pull/48521

ci: disable Renovate updates for `@angular/bazel`

---

modules/common/src/transfer_http.ts

TextEncoder is available for use in all browsers and Node.js versions supported by the Angular framework (https://caniuse.com/textencoder).

refactor(@nguniversal/common): remove old logic for arraybuffer

---

modules/common/src/transfer_http.ts

Currently, when using a post request the TransferHttpCache is invalidated, this is on the assumption that POST will mutate the previous GET requests. This however is very rare.
Closes #1795

fix(@nguniversal/common): avoid invalidating cache when using a post request

---

modules/builders/src/ssr-dev-server/index.ts
modules/builders/src/ssr-dev-server/schema.json
modules/builders/src/ssr-dev-server/schema.ts

This change adds the `--verbose` option to the SSR dev server.
closes #2909

feat(@nguniversal/builders): add `--verbose` option to SSR Dev Server

---

.circleci/config.yml
WORKSPACE
modules/builders/package.json
modules/common/package.json
modules/express-engine/package.json
package.json

BREAKING CHANGE: Node.js v14 support has been removed
Node.js v14 is planned to be End-of-Life on 2023-04-30. Angular will stop supporting Node.js v14 in Angular v16. Angular v16 will continue to officially support Node.js versions v16 and v18.

refactor(@nguniversal/common): remove Node.js v14 support

---

modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
modules/express-engine/schematics/install/index.spec.ts
modules/express-engine/schematics/install/index.ts
modules/express-engine/schematics/testing/test-app.ts

This commit add support to run `ng add @nguniversal/express-engine` in a standalone application.

feat(@nguniversal/express-engine): add standalone support to `ng add`

---

.circleci/config.yml
WORKSPACE
modules/builders/package.json
modules/common/package.json
modules/express-engine/package.json
package.json

This commit updates the minimum supported Node version across packages from 16.13.0 -> 16.14.0 to ensure compatibility with dependencies.

build: update minimum supported Node version from 16.13.0 -> 16.14.0

---

docs/transfer-http.md
modules/common/clover/src/transfer-http-cache/transfer-http-cache.module.ts

refactor(@nguniversal/common): remove usage of `BrowserTransferStateModule`

---

modules/builders/src/ssr-dev-server/index.spec.ts
modules/builders/src/ssr-dev-server/index.ts

Previously, for legacy reasons service workers were not served when using the `ssr-dev-server` builders. This commit enabled serving of service workers as now service workers can be served without valid SSL when served using localhost.

fix(@nguniversal/builders): add support to serve service workers

---

modules/common/clover/src/transfer-http-cache/transfer-http-cache.interceptor.ts
modules/common/src/transfer_http.ts

As per the discussion and @alan-agius4's point regarding the `TransferHttpResponse` shape under https://github.com/angular/angular/pull/49509. I suggest to align the status of optional and required keys of `TransferHttpResponse` interface of universal's interceptor to meet Angular's `packages/common/http/src/transfer_cache.ts `counterpart.

fix(@nguniversal/common): update TransferHttpResponse requiring body and headers

---

CHANGELOG.md

Cherry-picks the changelog from the "15.2.x" branch to the next branch (main).

docs: release notes for the v15.2.1 release

---

modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts

Without explicitly exporting the `bootstrap` as the default export from the `server.ts`, prerendering fails with the following message:
```
✖ Prerendering routes to /angular-universal-standalone/dist/angular-universal-standalone/browser failed.
Neither an AppServerModule nor a bootstrapping function was exported from: /angular-universal-standalone/dist/angular-universal-standalone/server/main.js.
```
Example repo is here with the fix https://github.com/brandonroberts/angular-v16-universal-standalone

fix(@nguniversal/express-engine): export default bootstrap in server template for standalone apps

---

CHANGELOG.md

Cherry-picks the changelog from the "16.0.x" branch to the next branch (main).

docs: release notes for the v16.0.0 release

---

integration/express-engine-ivy/angular.json
integration/express-engine-ivy/e2e/src/app.e2e-spec.ts
integration/express-engine-ivy/src/styles-extra.css
modules/common/engine/src/engine.ts

This commit fixes an issue with the regexp that caused incorrect output.
Closes #3128

fix(@nguniversal/common): correctly handle multiple lazy CSS files

---

CHANGELOG.md

Cherry-picks the changelog from the "16.0.x" branch to the next branch (main).

docs: release notes for the v16.0.2 release

---

modules/common/src/state-transfer-initializer/README.md
modules/common/src/state-transfer-initializer/module.ts
modules/common/src/transfer_http.ts

DEPRECATION: `StateTransferInitializerModule`, `TransferHttpCacheInterceptor` and `domContentLoadedFactory` have been deprecated in favor of `provideClientHydration`. See: https://angular.io/api/platform-browser/provideClientHydration

refactor: deprecate transfer http cache

---

CHANGELOG.md

Needed to manually put this together and accidentally linked to the wrong commit.

refactor: update changelog link for Critters version bump

---

modules/common/tools/src/inline-css-processor.ts

The problem with the previous approach is that it assumes that a `link` tag processed by Critters will be preceded by a `style` tag that was inserted by Critters. This assumption might not necessarily be true if Critters is unable to resolve the content of the linked styles.
Closes: #3241

fix(@nguniversal/common): error during critical CSS inlining for external stylesheets
