.travis.yml

we need to have travis running on each PR

chore: travis

---

scripts/gulp-tasks/task.serve.js

chore(build): fix gulp serve task allowing it to watch "js ts html" files

chore(build): fix gulp serve task

---

custom_typings/ng2.d.ts
index.js
modules/server/src/render.ts
modules/server/src/server_dom_renderer.ts
scripts/gulp-tasks/task.serve.js

fixes https://github.com/angular/universal/issues/26

implement ServerDomRenderer

---

examples/app/universal/app/App.ts
gulpfile.js
index.js
modules/server/src/helper.ts
modules/server/src/http_server.ts
package.json

Task https://github.com/angular/universal/issues/50

module(server) : Create NodeBackend for Http #50

---

examples/preboot/preboot.html
gulpfile.js
modules/preboot/src/client/dom.ts
modules/preboot/src/client/event_manager.ts
modules/preboot/src/interfaces/element.ts
modules/preboot/src/interfaces/preboot_ref.ts
modules/preboot/src/server/presets.ts
modules/preboot/test/client/dom_spec.ts
modules/preboot/test/client/event_manager_spec.ts
modules/preboot/test/server/presets_spec.ts

fix(preboot): maintain cursor position

---

custom_typings/ng2.d.ts
modules/server/server.ts
modules/server/src/server_router.ts
modules/server/test/server_router_spec.ts
tsconfig.json

PR for task #60 
@gdi2290 what do you think?

module(server): Create Node version for Router #60

---

examples/app/universal/app/App.ts
modules/server/src/bootstrap-server.ts
modules/server/src/render.ts

include styles above host component when rendering

feat(server): render style hosts with component

---

gulpfile.js
protractor.conf.js
test/test_page.e2e.js

PR for task https://github.com/angular/universal/issues/82
There is one failing test and 3 pending ones that need to be checked.

test(test_page.e2e.js): e2e test for ServerDomRenderer and with preboot.js

---

examples/preboot/preboot_example.html
gulpfile.js
modules/preboot/src/client/replay/replay_after_rerender.ts
modules/preboot/src/interfaces/element.ts
modules/preboot/src/server/presets.ts
modules/preboot/test/server/presets_spec.ts

fix(preboot): now checkboxes, radio buttons and select dropdowns work

---

tsconfig.json

fix(tsconfig): remove outdated tsd reference

---

README.md

Best practices for components as bullet points
related https://github.com/angular/universal/issues/124

docs(readme): best practices for components

---

modules/universal/server/src/express/engine.ts

fix(render): remove "enableProdMode" from render engine options

---

CONTRIBUTING.md

This fixes #62. This is not meant to be the final contributing guide, but we want to get something in there that we can then modify after some review by others.

docs(contributing) - Adding initial contributing guide

---

modules/angular2-express-engine/src/engine.ts

refactor(angular2-express-engine): import missing module  "renderToStringWithPreboot"

refactor(angular2-express-engine): import missing module 

---

modules/preboot/src/browser/dom.ts
modules/preboot/src/browser/event_manager.ts
modules/preboot/src/browser/preboot_browser.ts
modules/preboot/src/browser/replay/replay_after_rerender.ts
modules/preboot/src/interfaces/event.ts
modules/preboot/src/interfaces/preboot_ref.ts

fix(preboot): allow view without buffer

---

modules/grunt-prerender/src/prerender.ts
modules/gulp-prerender/src/prerender.ts
modules/webpack-prerender/src/prerender.ts

closes https://github.com/angular/universal/issues/312

refactor(prerenders): update gulp/grunt/webpack prerenders

---

modules/universal/src/node/platform/cookie.ts
modules/universal/src/node/platform/localStorage.ts
modules/universal/src/node/platform/title.ts

Initial implementation of an abstract classes for `Title`, `Cookie` and `LocalStorage`... (WIP)

feat(universal): add abstract classes for Title, Cookie and LocalStorage (wip)

---

modules/universal/src/node/platform/dom/node_dom_renderer.ts

No
- Add img attributes to `ATTRIBUTES` constant so `setElementProperty` can find them
This should fix #331.

fix(dom): add img attributes

---

CONTRIBUTING.md

Contribution document update. Inform people about `npm run install:all` and where modules are located, and how to get things started.

docs(contributing): Add repo install & start info

---

modules/preboot/package.json

- [x ] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [ x] preboot
Bumping preboot version and publishing to npm. Forgot to include that with last change.
n/a
n/a
No

refactor(preboot): bumping version and publishing

---

modules/polyfills/typings.json
modules/universal/typings.json
typings.json

chore(typings): Update deprecated

---

README.md

docs(readme): Add link to Universal Starter repo

---

modules/preboot/package.json
modules/preboot/src/browser/event_manager.ts

Bug fixes
Breaks on install with postinstall step and focus doesn't work
Install doesn't break now and focus works
No

fix(preboot): Fixing focus by adding a small timeout

---

modules/preboot/package.json
modules/preboot/src/browser/dom.ts
modules/preboot/src/browser/event_manager.ts

Fix for bug on focus selection
When focus occurs does not adhere to selection.
Cursor is placed in the appropriate place.
No

fix(preboot): fix for focus selection

---

modules/preboot/package.json
modules/preboot/src/browser/event_manager.ts

Wasn't working with autofocus before
If you have autofocus + preboot they collide and preboot focus doesn't work.
Now it works and focus set correctly.
No

fix(preboot): works with autofocus now

---

modules/broccoli-prerender/package.json

fix(broccoli-pretender): update to Angular Rc.1

---

modules/universal/src/node/http/node_http.ts

refactor - fix type
ngZome
ngZone
No
Small just fix typo

small: fix type zome -> zone

---

package.json

Windows fix, rimraf version update

(chore) Update to fix windows rm -rf

---

examples/package.json

`rm -rf` to `rimraf`
Added under devDepedencies as well.

chore(package): Update Examples to fix windows rm -rf

---

README.md

add ng-conf talk to readme

---

CONTRIBUTING.md

**DOCS**
Update docs to show `install:all` is no longer needed to be manually ran, showcase new `npm start` firing up examples. Showcase the different examples found under /examples. Also help with issues when installing (when getting latest etc) but showing `npm run clean:all` script.

docs(contributing): Fix install & start & explain examples

---

README.md

**docs**
Added .NET Core Universal repo
Put ngConf presentation at the top
**No**

docs(readme): Add .NET Core starter repo

---

modules/universal/src/node/bootloader.ts

fix(universal): patch for app crash (#425)

---

documentation/preboot/index.html
gulpfile.js

docs(documentation): Add broccoli-pretender and update other documents

---

README.md

Left wording to show older versions used deprecated router just in case.

doc(readme): show universal works w new router

---

modules/polyfills/package.json

- [V ] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [V ] Tests for the changes have been added (for bug fixes / features)
- [V] Docs have been added / updated (for bug fixes / features)
- [V ] universal
Bug fix
when trying to install the universal project using jspm, the message:
err  Installing npm:angular2-universal-polyfills@0.4.1, no version match for npm:zone.js@0.6.100
is thrown
* …

fix(polyfills) fixed zonejs version

---

modules/universal/src/node/platform/node.ts

Bug fix(#491)
Using the animation api result in the following error:
```
TypeError: Cannot read property 'animate' of undefined
at NodeDomRenderer.DomRenderer.animate (/home/mickael/spotlive/application/node_modules/@angular/platform-browser/src/dom/dom_renderer.js:226:37)
at Details_page_0_factory (Details.template.js:29:127)
at AppView._View_Details3.detectChangesInternal (Details.template.js:433:5)
at AppView.detectChanges …
```

fix(node platform): bugfix for angular animations (#491)

---

modules/universal/src/node/platform/dom/node_dom_renderer.ts

Was `else if (propertyValue = false)` needs the triple `===`

bug(NodeDomRenderer): Fix false flag for checked

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

chore(github): Issue template updates

---

modules/universal/src/node/router/node_platform_location.ts

Fixes #495 
For non base paths <base href="/myapp"> .

bug(NodePlatformLocation): Fix for non base location hrefs

---

modules/platform-node/parse5-adapter.ts

fix(parse5-usage): Fixed usage of the Parse5 serializer

---

.travis.yml
package.json

use npm-scripts https://docs.npmjs.com/misc/scripts
I think `npm test` is a major sequence to exec testing in npm packages.
No
none

feat(travis.yml): use npm scripts

---

DOCUMENTATION.md

Simply updated docs to match up with latest version of universal
Current docs reflect previous version of universal
No

docs(universal): Describe how to use universal

---

examples/express-aot/src/app.browser.module.ts
examples/express-aot/src/client.main.ts
examples/express-aot/src/server-express.ts
examples/express-aot/webpack.config-browser.js
examples/express-aot/webpack.config-server.js
modules/express-engine/src/index.ts
modules/platform-node/__private_imports__.ts
modules/platform-node/node-http.ts
modules/platform-node/node-platform.ts

(this PR points to the `update-angular-2-0-1` branch)

Get build passing for AOT example

---

modules/platform-node/parse5-adapter.ts

Fix treeAdapter
Add invoke, query, querySelector, querySelectorAll, userAgent functionality

fix(parse5adapter): Update parse5 to latest & fix functionality

---

modules/universal/src/browser/universal-module.ts

Fix this issue : https://github.com/angular/universal/issues/586
Error on Firefox version < 45
Support of Firefox version < 45
No

fix(universal-module): support for version < 45 of Firefox

---

modules/platform-node/node-http.ts

closes https://github.com/angular/universal/issues/589

fix(node-http): correctly set user-agent with normalized value

---

modules/platform-node/helper.ts

- **Please check if the PR fulfills these requirements**
- **What modules are related to this pull-request**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Removed implicit `any` from stringMapForEach in helper.ts
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

fix(platfrom-node): Remove implicit any from stringMapForEach callback

---

README.md

Updated to mirror starter repos "gotchas" & give some basic info on how the starters work.
Created a central location for the .NET Core starter repo as well.

docs(readme): update gotchas and starter repo info

---

README.md

docs(readme): settimeout gotcha

---

modules/platform-node/node-platform.ts

This adds fix that templates does not have to be inlined.
This PR still need discussion if it's available to use this without `moduleId: module.id` option to get relative paths to templates. After chatting with Patrick there might be an option to let AoT compiler inline all templates.
\cc @gdi2290

fix(node-platform): provide ResourceLoader for Templates that aren't inlined

---

README.md

Updated to fix link:
- Use a [UniversalCache](https://github.com/angular/universal-starter/blob/master/src/%2Bapp/shared/model/model.service.ts#L34-L50) instead of regular Http, to save certain requests so they aren't re-ran again on the Client. ([Example useage here](https://github.com/angular/universal-starter/blob/cc71e2d5b2d783f2bb52eebd1b5c6fa0ba23f08a/src/%2Bapp/%2Bhome/home.component.ts#L22-L24))

docs(readme): update universalcache gotcha

---

README.md

docs(readme): add universal-cli info

---

README.md

Fix typo: usage instead of useage

Fix(typo) usage instead of useage

---

modules/platform-node/node-renderer.ts

Fixes: https://github.com/angular/universal/pull/629#pullrequestreview-21082184
**Bug fix**
`false` being passed still hides the element (as it's turned into a string)
`false` no longer hides the element
**No**

fix(node-renderer): fix boolean false hiding elements

---

LICENSE

chore(License): update year

---

modules/ng-express-engine/README.md
modules/ng-express-engine/src/file-loader.ts
modules/ng-express-engine/src/main.ts

Feature
Non-AoT Modules are not supported by the express engine
Non-AoT Modules will be compiled, cached and then used for the request.
Module Factories which have been cached will be used for subsequent requests.
Bootstrapped Module Factories will be used to requests like normal 
No

feat(ng-express-engine): support non-aot

---

README.md

docs: add links to members profiles

---

modules/ng-express-engine/package.json

- To new package namespace.
- Use 4.0.0 @angular packages

fix(express-engine): Update package.json

---

README.md
UPGRADE-GUIDE.md

Basic upgrade guide added from `angular2-universal`

docs(upgrade): added angular2-universal upgrade guide

---

README.md

I think the PR form is overkill for the PR.

Grammatical tweak in README

---

modules/ng-express-engine/package.json
package.json

Updates dependencies in the main project
Adds Animations to the dependencies
Currently, animations is missing and the packages are out of date
Animations will no longer be missing and the packages will be up to date
No

chore(deps): update dependencies and add animations

---

build.sh
modules/ng-express-engine/package.json
modules/ng-express-engine/tsconfig.json
package.json
publish.sh

This adds scripts to publish modules
Currently, there are no scripts
To build distributables:
```sh
npm run build
```
To publish (if you have rights)
```sh
./publish.sh
```
No

build(publish): add scripts for publishing

---

modules/ng-express-engine/README.md

(docs) update README with correct package name

---

modules/ng-express-engine/tsconfig.json

Target ES5 in the build process
Currently targeting ES6, which breaks unit tests in PhantomJS (please see [this issue](https://github.com/angular/universal/issues/704))
Target ES5
No

fix(build): target es5 in ng-express-engine

---

.gitignore
build.sh
modules/ng-aspnetcore-engine/tsconfig.json
modules/ng-express-engine/tsconfig.json
package.json

Bug fix
Currently the module is compiled using tsc not allowing the request and response tokens to be statically analyzable
The module is compiled using ngc adding ng metadata to the tokens allowing them to be analyzable
No

build(engines): compile using ngc

---

.github/PULL_REQUEST_TEMPLATE.md

- Clean up pull request template of cruft
Clean up GitHub pull request template of bad copy/pasta
Two fields are already pre-filled with information that should not be in the template
N/A
No

chore(github): clean up pull request template

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

- Add code block formatting to checklist items to avoid them being rendered as tasks in the issue/pull request UI (also matches the core Angular repository template)
- Add in engines for selection

chore(github): add in code block formatting

---

package.json

```
```
```
```
Adding @types/express
Currently, there are no types for express
Types will be present for express, allowing strict compilation
No

chore(ng-express-engine): add @types/express

---

README.md

```
```
```
```
docs update
code example with old `Renderer` API
code example with new `Renderer2` API
no

docs(README): update renderer example for Renderer2

---

UPGRADE-GUIDE.md

* **Please check if the PR fulfils these requirements**
```
```
docs

docs(UPGRADE-GUIDE): add link to angular/universal-starter

---

package-lock.json
package.json
tsconfig.json

Pin to 2.3.4 to fix ngc errors

fix(package): pin typescript to fix ngc

---

.travis.yml

test: add build.sh as a Travis script

---

UPGRADE-GUIDE.md

```
```
```
```
docs update
broken link to Express Engine page: https://github.com/angular/universal/tree/master/modules/ng-express-engine
correct link to Express Engine page: https://github.com/angular/universal/tree/master/modules/express-engine
no breaking change

docs(UPGRADE-GUIDE): fix a broken link

---

README.md

```
```
```
```
update README.md
the highlight for typescript is disabled
the highlight for typescript is enabled
no breaking change

docs(README.md): enable highlight syntax for Typescript

---

README.md

Universal is now update to angular 5
```
```
```
```
Docs update
No

Version change in readme

---

README.md

```
```
```
```
Update readme.md
NA
NA
No

docs(readme): update roadmap

---

README.md

```
- [x ] Docs have been added / updated (for bug fixes / features)
```
```
```

docs(readme.md): added a missing space

---

modules/express-engine/package.json

fix(express-engine): node 9 strict engine error

---

modules/express-engine/README.md
modules/hapi-engine/README.md

```
```
```
```
* **What kind of change does this PR introduce?**
Docs update
* **What is the current behavior?**
See https://github.com/angular/universal/issues/918

docs(express, hapi): fix token import example

---

CHANGELOG.md

* Add missing breaking changes for secondary entrypoints to the CHANGELOG

chore: update CHANGELOG with breaking changes

---

modules/common/public-api.ts
modules/common/src/state-transfer-initilizer/README.md
modules/common/src/state-transfer-initilizer/module.ts

```
```
```
```
Adds a new module to help with StateTransfer
n/a
Adds a new module to delay the app starting, therefore delay statetransfer accessing the dom till it's ready

feat(common): introduce StateTransferInitializerModule

---

README.md

```
```
Renames "Angular 2" to "Angular"
Angular naming convention

docs(README): rename "Angular 2" to "Angular"

---

modules/aspnetcore-engine/README.md
modules/express-engine/README.md
modules/hapi-engine/README.md

```
- [*] The commit message follows [our guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format)
- [*] Tests for the changes have been added (for bug fixes / features)
- [*] Docs have been added / updated (for bug fixes / features)
```
```
- [*] express-engine
```
Bug fix
Just fix the documentation
Nothing
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application …

Fix import of REQUEST token

---

modules/express-engine/BUILD.bazel
modules/express-engine/spec/index.spec.ts
tools/package-tools/rollup-globals.ts
tsconfig.json
tslint.json
yarn.lock

Some super basic unit testing for express-engine. But it shows a few issues so far.

test(express-engine): add basic unit tests

---

README.md

What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```
Issue Number: N/A
```
[ ] Yes
[x] No
```

docs: update readme to acknowledge Angular 6

---

modules/aspnetcore-engine/tokens/public-api.ts
modules/express-engine/tokens/public-api.ts
modules/hapi-engine/tokens/public-api.ts

refactor: remove unsed files

---

modules/common/engine/BUILD.bazel
modules/common/tokens/BUILD.bazel

fix(common): fixup secondary entrypoints

---

modules/aspnetcore-engine/BUILD.bazel
modules/common/BUILD.bazel
modules/express-engine/BUILD.bazel
modules/hapi-engine/BUILD.bazel
modules/module-map-ngfactory-loader/BUILD.bazel
modules/socket-engine/BUILD.bazel
publish-next.sh
publish.sh

Credit to @vikerman for the contents of this PR. Running on a branch on the main repo to see if the integration tests pass.
PR close #1058

build: publish only ng_package-s tagged with 'release'

---

modules/express-engine/schematics/install/files/root/__serverFileName@stripTsExtension__.ts

`// Server static files` -> `// Serve static files`

Fix typo in express template

---

modules/express-engine/schematics/install/files/root/__serverFileName@stripTsExtension__.ts

fix(express-engine): remove unneeded dep from schematics server

---

integration/express-engine/e2e/helloworld-spec.ts
integration/express-engine/src/helloworld/hello-world.component.ts
integration/express-engine/src/server.ts
integration/hapi-engine/e2e/helloworld-spec.ts
integration/hapi-engine/src/helloworld/hello-world.component.ts
integration/module-map-ngfactory-loader/e2e/helloworld-spec.ts
modules/hapi-engine/src/main.ts

small test to ensure that window.location is populated by what we provide to the engine which should be populated by platform-server

test: add tests to ensure that document.location is populated

---

package.json
yarn.lock

build: sync minor version of domino with framework

---

docs/transfer-http.md

Improve documentation for requests other than GET, See issue: #1181

Update documentation for TransferHttpCacheModule

---

integration/express-engine-ivy/angular.json
integration/express-engine-ve/angular.json
integration/hapi-engine-ivy/angular.json
integration/hapi-engine-ve/angular.json

Update tests to reflect latest project configuration
See: https://github.com/angular/angular-cli/pull/15651

tests: update optimization setting for integration tests

---

modules/builders/BUILD.bazel
modules/builders/README.md
modules/builders/builders.json
modules/builders/package.json
modules/builders/src/index.ts
modules/builders/src/ssr-dev-server/index.ts
modules/builders/src/ssr-dev-server/schema.json
modules/builders/src/ssr-dev-server/schema.ts
package.json
yarn.lock

Note: there is no testing setup yet. But this should be enough to get started
//cc @manfredsteyer

Builders package skeleton

---

modules/builders/BUILD.bazel
modules/builders/package.json
tools/defaults.bzl

- include package.json in the npm package
- use templated version numbers for dependencies
- add @nguniversal/builders to the ng update package group (and remove @nguniversal/modulemap-factory-loader)

fix(builders): fix package.json

---

modules/common/schematics/BUILD.bazel
modules/common/schematics/add/index.spec.ts
modules/common/schematics/add/index.ts
modules/common/schematics/migrations/update-9/index.spec.ts
modules/common/schematics/migrations/update-9/index.ts
modules/common/schematics/testing/test-app.ts
modules/common/schematics/utils/utils.ts
modules/express-engine/package.json
modules/express-engine/schematics/collection.json
modules/express-engine/schematics/install/index.spec.ts
modules/express-engine/schematics/install/index.ts
modules/express-engine/schematics/migrations/migration-collection.json
modules/express-engine/schematics/migrations/update-9/index.spec.ts
modules/express-engine/schematics/migrations/update-9/index.ts
modules/express-engine/schematics/testing/test-app.ts
modules/hapi-engine/package.json
modules/hapi-engine/schematics/install/index.spec.ts
modules/hapi-engine/schematics/install/index.ts
modules/hapi-engine/schematics/migrations/migration-collection.json
modules/hapi-engine/schematics/migrations/update-9/index.spec.ts
modules/hapi-engine/schematics/migrations/update-9/index.ts
modules/hapi-engine/schematics/testing/test-app.ts
package.json
yarn.lock

Note: the migrations are currently being tested on via unit tests since there is no real E2E infra in this repo.

feat: add migrations for version 9

---

modules/builders/src/ssr-dev-server/index.ts
modules/builders/src/ssr-dev-server/utils.ts

fix(builders): display server console message

---

modules/builders/src/prerender/index.spec.ts
modules/builders/src/prerender/index.ts

fix(builder): update prerender error message

---

integration/express-engine-ivy-prerender/e2e/protractor.conf.js
integration/express-engine-ivy-prerender/e2e/src/app.e2e-spec.ts
integration/express-engine-ivy-prerender/src/app/pokedex/pokedex.component.ts
integration/express-engine-ivy-prerender/src/app/pokemon.service.ts
modules/builders/src/prerender/index.spec.ts
modules/builders/src/prerender/index.ts

Fixes [Issue #1375](https://github.com/angular/universal/issues/1375)

fix(builder): allow prerender of nested paths

---

.github/ISSUE_TEMPLATE/Bug.md
.github/ISSUE_TEMPLATE/Feature_Request.md

Make the templates more similar to Angular FW and CLI

docs: update issue templates

---

modules/common/schematics/add/index.ts

feat(prerender): add "/" as the default route in angular.json

---

modules/builders/src/ssr-dev-server/index.ts

In some cases, we spawned the server to early, which caused the views not to be found. This happened when the browser build too a long time.
With this change we spawn the server only after both browser and server have emitted.
//cc @mgechev

fix(builders): don't spawn server until browser build finishes

---

modules/module-map-ngfactory-loader/README.md

Patch version of https://github.com/angular/universal/pull/1589

docs: @nguniversal/module-map-ngfactory-loader deprecation notice

---

integration/express-engine-ivy-prerender/tsconfig.server.json
integration/express-engine-ivy/tsconfig.server.json
integration/express-engine-ve/tsconfig.server.json
integration/hapi-engine-ivy/tsconfig.server.json
integration/hapi-engine-ve/tsconfig.server.json

See: https://github.com/angular/angular-cli/pull/17352

tests: remove module from tsconfig.server.json

---

README.md

Hey, I just fixed a typo in readme

📝 docs: fix existing typo in readme

---

integration/express-engine-ivy-prerender/angular.json
modules/builders/BUILD.bazel
modules/builders/src/prerender/index.ts
modules/builders/src/prerender/render.ts
modules/builders/src/prerender/utils.spec.ts
modules/builders/src/prerender/utils.ts

fix(prerender): use browser builder's index option

---

modules/builders/package.json

[master] @nguniversal/builders package improvements

---

modules/aspnetcore-engine/package.json
modules/common/package.json
modules/express-engine/package.json
modules/hapi-engine/package.json
modules/module-map-ngfactory-loader/package.json
modules/socket-engine/package.json
package.json

The Angular FW does support Node 14
Closes: #1686

feat: remove engine restriction of >=10.13.0 <13.0.0

---

.github/ISSUE_TEMPLATE/Bug.md
docs/gotchas.md

The Gotchas guide hasn't been updated in quite some time. This
refresh adds a more structured layout with explicit examples
and solutions for the most common issues.
This also updates the issue template to add a note about what
constitutes an appropriate issue, and a link to the gotchas guide.

docs: update issue template and Gotchas guide

---

.github/ISSUE_TEMPLATE/Bug.md

The bug template is not showing

docs: fix bug template

---

modules/builders/BUILD.bazel
modules/builders/src/prerender/index.spec.ts
modules/builders/src/prerender/index.ts
modules/builders/testing/hello-world-app/angular.json
package.json
yarn.lock

feat(builders): support service worker generation with prerendering

---

renovate.json

Use the new unified target label system
https://github.com/angular/angular-cli/pull/19580

ci: update remaining reference to old pr targeting system

---

modules/common/engine/src/engine.ts

First steps to make this API public.

refactor(common): mark private methods with private keyword

---

modules/hapi-engine/package.json

fix(@nguniversal/hapi-engine): fix incorrect peer dependency on hapi

---

modules/common/engine/src/engine.ts

fix(@nguniversal/common-engine): ReferenceError: URL is not defined

---

package.json
renovate.json

Master should be v12 now that 11.2.x branch has been cut.

build: bump version on master to v12.0.0-next.0

---

integration/clover/angular.json
integration/clover/package.json
integration/clover/src/app/app-routing.module.ts
integration/clover/src/app/app.component.ts
integration/clover/src/app/app.module.ts
integration/clover/src/app/app.server.module.ts
integration/clover/src/app/homepage.component.ts
integration/clover/src/app/pokedex.component.ts
integration/clover/src/app/pokemon.service.ts
integration/clover/test.js
modules/builders/BUILD.bazel
modules/builders/builders.json
modules/builders/package.json
modules/builders/src/static-generator/index.ts
modules/builders/src/static-generator/schema.json
modules/builders/src/static-generator/schema.ts
modules/builders/src/static-generator/utils.ts
modules/builders/src/static-generator/worker.ts
package.json

With this change we create a builder that can be used to generate static pages (prerendering) using the new Universal approach (Clover).

feat(@nguniversal/builders): add static page generator builder using Angular SSR Clover

---

modules/common/clover/server/src/server-engine.ts
modules/common/schematics/ng-add/files/src/server.ts.template

fix(@nguniversal/common): correctly construct host string

---

modules/common/engine/src/engine.ts

https://github.com/angular/universal/blob/master/modules/common/engine/src/engine.ts#L31

fix(@nguniversal/common-engine):  `inlineCriticalCss` defaults to false

---

.ng-dev/config.ts
.ng-dev/github.ts
.ng-dev/pull-request.ts
package.json
renovate.json
yarn.lock

More info: https://github.com/angular/dev-infra/commit/c3f5729376048af3ce939a505e5389dba11ff7d2

build: replace ng-dev MergeConfig wiith PullRequestConfig

---

WORKSPACE

build: update Bazel Node.js version to `14.17.1`

---

CHANGELOG.md
package.json

Manually added a changelog entry for TS 4.6 since that's the only change here.

Bump version to "v13.1.0" with changelog.

---

.github/ISSUE_TEMPLATE/Bug.md
.github/PULL_REQUEST_TEMPLATE/Improvement.md
.github/PULL_REQUEST_TEMPLATE/New_Feature.md
CONTRIBUTING.md
README.md
docs/angular2-universal-migration.md
integration/clover/README.md
integration/common-engine/README.md
integration/express-engine-ivy-hybrid/README.md
integration/express-engine-ivy-hybrid/server.ts
integration/express-engine-ivy/README.md
integration/express-engine-ivy/server.ts
modules/builders/testing/hello-world-app/README.md
modules/common/README.md
modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts

Cleans up all referneces to the old `master` branch.
cc. @alan-agius4

build: clean up references to old `master` branch

---

.github/workflows/dev-infra.yml
.github/workflows/lock-closed.yml
.github/workflows/scorecard.yml
package.json
yarn.lock

Backport several Renovate commits.

Add missing commits

---

modules/builders/src/prerender/index.ts
modules/builders/src/static-generator/index.ts

fix(@nguniversal/builders): correctly handle path normalizations on Windows

---

CHANGELOG.md
package.json

The previous "next" release-train has moved into the release-candidate phase. This PR updates the next branch to the subsequent release-train.
Also this PR cherry-picks the changelog for v14.1.0-rc.0 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v14.2.0-next.0".

---

integration/common-engine/src/main.server.ts
integration/express-engine-ivy-hybrid/e2e/src/util.ts
integration/express-engine-ivy-hybrid/src/main.server.ts
integration/express-engine-ivy/src/main.server.ts
modules/builders/BUILD.bazel
modules/builders/src/prerender/index.spec.ts
modules/builders/src/prerender/index.ts
modules/builders/src/prerender/worker.ts
modules/builders/testing/hello-world-app/src/main.server.ts
modules/common/engine/src/engine.ts
tools/defaults.bzl
yarn.lock

Add rendering context.

---

docs/transfer-http.md

docs: update transfer-http docs

---

integration/clover/angular.json
integration/common-engine/angular.json
integration/common-engine/e2e/protractor.conf.js
integration/common-engine/package.json
integration/express-engine-ivy-hybrid/e2e/protractor.conf.js
integration/express-engine-ivy-hybrid/package.json
integration/express-engine-ivy/angular.json
integration/express-engine-ivy/e2e/protractor.conf.js
integration/express-engine-ivy/package.json
modules/builders/testing/hello-world-app/angular.json
package.json
yarn.lock

These depedencies are no longer needed.

build: delete un-needed dependencies

---

integration/common-engine/server.ts
integration/express-engine-ivy-hybrid/server.ts
integration/express-engine-ivy/server.ts
modules/builders/testing/hello-world-app/server.ts
modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts

Replace the old style import with the new one.

fix(@nguniversal/express-engine): replace zone.js import

---

modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
modules/express-engine/schematics/install/index.spec.ts

The `server.ts` is missing a single tick on the import

fix(@nguniversal/express-engine): update import for template server file

---

.bazelversion
WORKSPACE
modules/bazel-tsconfig-build.json
package.json
tools/defaults.bzl
tools/postinstall/patches/@angular+bazel+16.0.0-next.6.patch
tools/postinstall/patches/@bazel+concatjs+5.8.1.patch
tsconfig.json
yarn.lock

This commit update tooling to generate APF version 16 distributables.

build: build packages in APF version 16 format

---

modules/builders/src/ssr-dev-server/index.spec.ts
modules/builders/src/ssr-dev-server/index.ts

fix(@nguniversal/builders): strip out newlines

---

modules/builders/src/prerender/index.spec.ts
modules/common/package.json
package.json
yarn.lock

build: update dependency critters to v0.0.19

---

modules/common/package.json
package.json
yarn.lock

Update to latest version of critters.
(cherry picked from commit 2b0f8c2bf692c58a823ac5731af5107ee4f808cd)
`16.1.x` specific PR cherry picked from https://github.com/angular/universal/pull/3215.

build: update critters

---

CHANGELOG.md

Needed to manually put this together and accidentally linked to the wrong commit.

refactor: update changelog link for Critters version bump

---

modules/common/engine/src/engine.ts

Prior to this change, we did not check for the server context which is some cases caused the app-shell to be served instead of the SSR version.

fix(@nguniversal/common): check for server context when doing hybrid rendering
